services:
  - type: web
    name: selection-sort
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:10000 selection:app"
    envVars:
      - key: FLASK_ENV
        value: production